# Defines a default set of lint rules to enforce
include: package:lints/recommended.yaml

# For lint rules and documentation, see https://dart.dev/tools/linter-rules
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
   exclude:
     - build/**
